#!/bin/bash

mvn clean
mvn package -Dmaven.test.skip=true
if [ $? -ne 0 ]; then
    exit 1
fi

cp target/lottery-mvc-1.0-SNAPSHOT.war target/lottery.war

cp -r target/lottery-mvc-1.0-SNAPSHOT target/lottery
mv target/lottery/WEB-INF/lib/qinyuan*.jar target/lottery/WEB-INF/
rm -rf target/lottery/WEB-INF/lib/* target/lottery/WEB-INF/classes/{hibernate*,global-config*,log*}
mv target/lottery/WEB-INF/qinyuan*.jar target/lottery/WEB-INF/lib/
cd target/lottery
tar -zcf lottery.tar.gz *
mv lottery.tar.gz ../
#cd ../
#rm -rf  ./lottery
